# Generated by Django 5.1.5 on 2025-02-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_id', models.IntegerField()),
                ('resume', models.TextField()),
                ('prompt', models.TextField()),
            ],
        ),
    ]
