# Generated by Django 5.1.5 on 2025-02-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0002_endpoint_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='prompt',
            new_name='job_description',
        ),
    ]
